apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 3 #I don't have a big enough cluster to have more than 1, just pretend it's there :D
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      volumes:
        - name: clickhouse-userconfigmap
          configMap:
            name: clickhouse-userconfigmap
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
        - containerPort: 9000
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 2Gi
        volumeMounts:
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/users.xml
              subPath: users.xml
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/users.d/default.xml
              subPath: access_management.xml
            - name: clickhouse-userconfigmap
              mountPath: /etc/clickhouse-server/config.d/default_config.xml
              subPath: storage.xml
            - name: clickhouse-storage
              mountPath: /data
