apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  namespace: clickhouse
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  hostPath:
    path: /data
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: clickhouse-pvc
    namespace: clickhouse