apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  selector:
    app: clickhouse
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: replication
      protocol: TCP
      port: 9009
      targetPort: 9009